// favoriten.js
const meineLieblingsSeiten = [
    { title: "Glaggle", desc: "Glaggle Your life!", url: "https://glaggle.ch" },
    { title: "YouTube", desc: "Schaue die neuesten Videos weltweit.", url: "https://youtube.com" },
    { title: "Glaggle Zahlenraten", desc: "Ein lustiges Spiel, um Zahlen zu erraten.", url: "https://glaggle.ch/zahlenraten" },
    { title: "Glame AI", desc: "Nutze den intelligenten Ki Chatbot von Glaggle", url: "https://glaggle.ch/glame" },
    { title: "Glaggle Mail", desc: "Sichere E-Mails für dein Glaggle-Konto.", url: "https://mail.glaggle.ch" },
    { title: "Facebook", desc: "Vernetze dich mit Freunden und der Welt.", url: "https://facebook.com" },
    { title: "Instagram", desc: "Teile Fotos und Videos mit deinen Followern.", url: "https://instagram.com" },
    { title: "TikTok", desc: "Kurzvideos, die Trends setzen.", url: "https://tiktok.com" },
    { title: "X (Twitter)", desc: "Echtzeit-Nachrichten und Diskussionen.", url: "https://x.com" },
    { title: "LinkedIn", desc: "Das Netzwerk für berufliche Kontakte.", url: "https://linkedin.com" },
    { title: "Reddit", desc: "Die Startseite des Internets für Foren.", url: "https://reddit.com" },
    { title: "Pinterest", desc: "Entdecke Rezepte, Deko-Ideen und Inspiration.", url: "https://pinterest.com" },
    { title: "Discord", desc: "Chatten und Communities für Gamer und Creator.", url: "https://discord.com" },
    { title: "WhatsApp", desc: "Messenger für Text und Telefonie.", url: "https://web.whatsapp.com" },
    { title: "Telegram", desc: "Sicherer Cloud-basierter Messenger.", url: "https://telegram.org" },
    { title: "Wikipedia", desc: "Die freie Enzyklopädie.", url: "https://wikipedia.org" },
    { title: "Google Maps", desc: "Finde Routen und Orte weltweit.", url: "https://maps.google.com" },
    { title: "DeepL", desc: "Der präziseste Übersetzer der Welt.", url: "https://deepl.com" },
    { title: "Quora", desc: "Fragen stellen und Wissen teilen.", url: "https://quora.com" },
    { title: "Stack Overflow", desc: "Die größte Community für Programmierer.", url: "https://stackoverflow.com" },
    { title: "GitHub", desc: "Hoste und verwalte deinen Code.", url: "https://github.com" },
    { title: "Medium", desc: "Plattform für tiefgründige Artikel und Blogs.", url: "https://medium.com" },
    { title: "Amazon", desc: "Alles finden, vergleichen und kaufen.", url: "https://amazon.de" },
    { title: "eBay", desc: "Kaufen und Verkaufen von Neu- und Gebrauchtware.", url: "https://ebay.de" },
    { title: "Etsy", desc: "Handgemachtes, Vintage und Kreatives.", url: "https://etsy.com" },
    { title: "AliExpress", desc: "Globaler Marktplatz für günstige Produkte.", url: "https://aliexpress.com" },
    { title: "Netflix", desc: "Serien und Filme online streamen.", url: "https://netflix.com" },
    { title: "Twitch", desc: "Live-Streaming von Games und Entertainment.", url: "https://twitch.tv" },
    { title: "Spotify", desc: "Millionen von Songs und Podcasts.", url: "https://spotify.com" },
    { title: "Disney+", desc: "Die Heimat von Disney, Pixar und Marvel.", url: "https://disneyplus.com" },
    { title: "Steam", desc: "Die ultimative Plattform für PC-Spiele.", url: "https://steampowered.com" },
    { title: "SRF", desc: "Schweizer Radio und Fernsehen - News und Unterhaltung.", url: "https://srf.ch" },
    { title: "NZZ", desc: "Neue Zürcher Zeitung - Hochwertiger Journalismus.", url: "https://nzz.ch" },
    { title: "Tages-Anzeiger", desc: "Aktuelle Nachrichten aus Zürich und der Welt.", url: "https://tagesanzeiger.ch" },
    { title: "20 Minuten", desc: "Die meistgelesene Gratiszeitung der Schweiz.", url: "https://20min.ch" },
    { title: "Blick", desc: "Nachrichten, Sport und People-News.", url: "https://blick.ch" },
    { title: "Watson", desc: "News, Unterhaltung und Debatten für die Schweiz.", url: "https://watson.ch" },
    { title: "RTS", desc: "Radio Télévision Suisse - Westschweizer Rundfunk.", url: "https://rts.ch" },
    { title: "Tagesschau", desc: "Deutschlands wichtigste Nachrichtensendung.", url: "https://tagesschau.de" },
    { title: "ZDF heute", desc: "Nachrichten des Zweiten Deutschen Fernsehens.", url: "https://zdf.de/nachrichten" },
    { title: "Der Spiegel", desc: "Investigativer Journalismus und aktuelle News.", url: "https://spiegel.de" },
    { title: "Die Zeit", desc: "Analysen, Hintergründe und Politik.", url: "https://zeit.de" },
    { title: "ORF", desc: "Österreichischer Rundfunk - News und TV.", url: "https://orf.at" },
    { title: "Der Standard", desc: "Qualitätsjournalismus aus Österreich.", url: "https://derstandard.at" },
    { title: "Süddeutsche Zeitung", desc: "Überregionale Tageszeitung aus München.", url: "https://sueddeutsche.de" },
    { title: "FAZ", desc: "Frankfurter Allgemeine Zeitung.", url: "https://faz.net" },
    { title: "Handelsblatt", desc: "Wirtschafts- und Finanznachrichten.", url: "https://handelsblatt.com" },
    { title: "BBC News", desc: "World news and international analysis.", url: "https://bbc.com/news" },
    { title: "CNN", desc: "Breaking news and video from around the world.", url: "https://cnn.com" },
    { title: "The New York Times", desc: "International and US news, opinion and culture.", url: "https://nytimes.com" },
    { title: "The Guardian", desc: "Independent world news and liberal opinion.", url: "https://theguardian.com" },
    { title: "Reuters", desc: "Global news agency for business and politics.", url: "https://reuters.com" },
    { title: "Associated Press", desc: "Independent news from every corner of the globe.", url: "https://apnews.com" },
    { title: "Al Jazeera", desc: "Breaking news and analysis from the Middle East.", url: "https://aljazeera.com" },
    { title: "The Wall Street Journal", desc: "Business and stock market news.", url: "https://wsj.com" },
    { title: "Bloomberg", desc: "Global business and financial data.", url: "https://bloomberg.com" },
    { title: "The Economist", desc: "World politics, business and finance.", url: "https://economist.com" },
    { title: "TIME", desc: "Politics, history and world events.", url: "https://time.com" },
    { title: "National Geographic", desc: "Science, nature and exploration.", url: "https://nationalgeographic.com" },
    { title: "The Washington Post", desc: "Democracy dies in darkness.", url: "https://washingtonpost.com" },
    { title: "Forbes", desc: "Business, technology and leadership.", url: "https://forbes.com" },
    { title: "Heise Online", desc: "IT-News und Hintergründe aus Deutschland.", url: "https://heise.de" },
    { title: "The Verge", desc: "Tech, science, art and culture.", url: "https://theverge.com" },
    { title: "Wired", desc: "The future of business, tech and culture.", url: "https://wired.com" },
    { title: "TechCrunch", desc: "Startup news and technology analysis.", url: "https://techcrunch.com" },
    { title: "Engadget", desc: "The original home for gadget news.", url: "https://engadget.com" },
    { title: "IGN", desc: "Everything for video games and movies.", url: "https://ign.com" },
    { title: "GameStar", desc: "Deutschlands größte PC-Spiele-Seite.", url: "https://gamestar.de" },
    { title: "Golem.de", desc: "IT-News für Profis.", url: "https://golem.de" },
    { title: "Scientific American", desc: "Science news and research.", url: "https://scientificamerican.com" },
    { title: "Nature", desc: "The leading international weekly journal of science.", url: "https://nature.com" },
    { title: "Kicker", desc: "Deutschlands Sportmagazin Nr. 1.", url: "https://kicker.de" },
    { title: "Sky Sport", desc: "Live-Sport und News.", url: "https://skysport.de" },
    { title: "ESPN", desc: "Global sports coverage.", url: "https://espn.com" },
    { title: "Vogue", desc: "Fashion, beauty and culture.", url: "https://vogue.com" },
    { title: "Rolling Stone", desc: "Music, politics and culture.", url: "https://rollingstone.com" },
    { title: "BZ Basel", desc: "Nachrichten aus der Region Basel.", url: "https://bzbasel.ch" },
    { title: "Berner Zeitung", desc: "News aus Bern und Umgebung.", url: "https://bernerzeitung.ch" },
    { title: "Luzerner Zeitung", desc: "Zentralschweizer Nachrichten.", url: "https://luzernerzeitung.ch" },
    { title: "St. Galler Tagblatt", desc: "Nachrichten aus der Ostschweiz.", url: "https://tagblatt.ch" },
    { title: "ProSieben", desc: "Entertainment und Serien.", url: "https://prosieben.de" },
    { title: "RTL News", desc: "Aktuelle News und Videos.", url: "https://rtl.de" },
    { title: "Arte", desc: "Der europäische Kultursender.", url: "https://arte.tv" },
    { title: "Euronews", desc: "Europäische Perspektiven auf Weltnachrichten.", url: "https://euronews.com" },
    { title: "Business Insider", desc: "Wirtschaftsnews für die junge Generation.", url: "https://businessinsider.de" },
    { title: "PC Welt", desc: "Tipps und News rund um den PC.", url: "https://pcwelt.de" },
    { title: "CHIP", desc: "Tests, Downloads und Technik-Ratgeber.", url: "https://chip.de" },
    { title: "Spektrum der Wissenschaft", desc: "Fundierte Berichte aus der Forschung.", url: "https://spektrum.de" }
];
