// favoriten.js
const meineLieblingsSeiten = [
    { title: "Glaggle", desc: "Glaggle Your life!", url: "https://glaggle.ch" },
    { title: "YouTube", desc: "Schaue die neuesten Videos weltweit.", url: "https://youtube.com" },
    { title: "Glaggle Zahlenraten", desc: "Ein lustiges Spiel, um Zahlen zu erraten.", url: "https://glaggle.ch/zahlenraten" },
    { title: "Glame AI", desc: "Nutze den intelligenten KI Chatbot von Glaggle", url: "https://glaggle.ch/glame" },
    { title: "Glaggle Mail", desc: "Sichere E-Mails für dein Glaggle-Konto.", url: "https://mail.glaggle.ch" },
    { title: "Facebook", desc: "Vernetze dich mit Freunden und der Welt.", url: "https://facebook.com" },
    { title: "Instagram", desc: "Teile Fotos und Videos mit deinen Followern.", url: "https://instagram.com" },
    { title: "TikTok", desc: "Kurzvideos, die Trends setzen.", url: "https://tiktok.com" },
    { title: "X (Twitter)", desc: "Echtzeit-Nachrichten und Diskussionen.", url: "https://x.com" },
    { title: "LinkedIn", desc: "Das Netzwerk für berufliche Kontakte.", url: "https://linkedin.com" },
    { title: "Reddit", desc: "Die Startseite des Internets für Foren.", url: "https://reddit.com" },
    { title: "Pinterest", desc: "Entdecke Rezepte, Deko-Ideen und Inspiration.", url: "https://pinterest.com" },
    { title: "Discord", desc: "Chatten und Communities für Gamer und Creator.", url: "https://discord.com" },
    { title: "WhatsApp", desc: "Messenger für Text und Telefonie.", url: "https://web.whatsapp.com" },
    { title: "Telegram", desc: "Sicherer Cloud-basierter Messenger.", url: "https://telegram.org" },
    { title: "Wikipedia", desc: "Die freie Enzyklopädie.", url: "https://wikipedia.org" },
    { title: "Google Maps", desc: "Finde Routen und Orte weltweit.", url: "https://maps.google.com" },
    { title: "DeepL", desc: "Der präziseste Übersetzer der Welt.", url: "https://deepl.com" },
    { title: "Quora", desc: "Fragen stellen und Wissen teilen.", url: "https://quora.com" },
    { title: "Stack Overflow", desc: "Die größte Community für Programmierer.", url: "https://stackoverflow.com" },
    { title: "GitHub", desc: "Hoste und verwalte deinen Code.", url: "https://github.com" },
    { title: "Medium", desc: "Plattform für tiefgründige Artikel und Blogs.", url: "https://medium.com" },
    { title: "Amazon", desc: "Alles finden, vergleichen und kaufen.", url: "https://amazon.de" },
    { title: "eBay", desc: "Kaufen und Verkaufen von Neu- und Gebrauchtware.", url: "https://ebay.de" },
    { title: "Etsy", desc: "Handgemachtes, Vintage und Kreatives.", url: "https://etsy.com" },
    { title: "AliExpress", desc: "Globaler Marktplatz für günstige Produkte.", url: "https://aliexpress.com" },
    { title: "Netflix", desc: "Serien und Filme online streamen.", url: "https://netflix.com" },
    { title: "Twitch", desc: "Live-Streaming von Games und Entertainment.", url: "https://twitch.tv" },
    { title: "Spotify", desc: "Millionen von Songs und Podcasts.", url: "https://spotify.com" },
    { title: "Disney+", desc: "Die Heimat von Disney, Pixar und Marvel.", url: "https://disneyplus.com" },
    { title: "Steam", desc: "Die ultimative Plattform für PC-Spiele.", url: "https://steampowered.com" },
    { title: "SRF", desc: "Schweizer Radio und Fernsehen - News und Unterhaltung.", url: "https://srf.ch" },
    { title: "NZZ", desc: "Neue Zürcher Zeitung - Hochwertiger Journalismus.", url: "https://nzz.ch" },
    { title: "Tages-Anzeiger", desc: "Aktuelle Nachrichten aus Zürich und der Welt.", url: "https://tagesanzeiger.ch" },
    { title: "20 Minuten", desc: "Die meistgelesene Gratiszeitung der Schweiz.", url: "https://20min.ch" },
    { title: "Blick", desc: "Nachrichten, Sport und People-News.", url: "https://blick.ch" },
    { title: "Watson", desc: "News, Unterhaltung und Debatten für die Schweiz.", url: "https://watson.ch" },
    { title: "RTS", desc: "Radio Télévision Suisse - Westschweizer Rundfunk.", url: "https://rts.ch" },
    { title: "Tagesschau", desc: "Deutschlands wichtigste Nachrichtensendung.", url: "https://tagesschau.de" },
    { title: "ZDF heute", desc: "Nachrichten des Zweiten Deutschen Fernsehens.", url: "https://zdf.de/nachrichten" },
    { title: "Der Spiegel", desc: "Investigativer Journalismus und aktuelle News.", url: "https://spiegel.de" },
    { title: "Die Zeit", desc: "Analysen, Hintergründe und Politik.", url: "https://zeit.de" },
    { title: "ORF", desc: "Österreichischer Rundfunk - News und TV.", url: "https://orf.at" },
    { title: "Der Standard", desc: "Qualitätsjournalismus aus Österreich.", url: "https://derstandard.at" },
    { title: "Süddeutsche Zeitung", desc: "Überregionale Tageszeitung aus München.", url: "https://sueddeutsche.de" },
    { title: "FAZ", desc: "Frankfurter Allgemeine Zeitung.", url: "https://faz.net" },
    { title: "Handelsblatt", desc: "Wirtschafts- und Finanznachrichten.", url: "https://handelsblatt.com" },
    { title: "BBC News", desc: "World news and international analysis.", url: "https://bbc.com/news" },
    { title: "CNN", desc: "Breaking news and video from around the world.", url: "https://cnn.com" },
    { title: "The New York Times", desc: "International and US news, opinion and culture.", url: "https://nytimes.com" },
    { title: "The Guardian", desc: "Independent world news and liberal opinion.", url: "https://theguardian.com" },
    { title: "Reuters", desc: "Global news agency for business and politics.", url: "https://reuters.com" },
    { title: "Associated Press", desc: "Independent news from every corner of the globe.", url: "https://apnews.com" },
    { title: "Al Jazeera", desc: "Breaking news and analysis from the Middle East.", url: "https://aljazeera.com" },
    { title: "The Wall Street Journal", desc: "Business and stock market news.", url: "https://wsj.com" },
    { title: "Bloomberg", desc: "Global business and financial data.", url: "https://bloomberg.com" },
    { title: "The Economist", desc: "World politics, business and finance.", url: "https://economist.com" },
    { title: "TIME", desc: "Politics, history and world events.", url: "https://time.com" },
    { title: "National Geographic", desc: "Science, nature and exploration.", url: "https://nationalgeographic.com" },
    { title: "The Washington Post", desc: "Democracy dies in darkness.", url: "https://washingtonpost.com" },
    { title: "Forbes", desc: "Business, technology and leadership.", url: "https://forbes.com" },
    { title: "Heise Online", desc: "IT-News und Hintergründe aus Deutschland.", url: "https://heise.de" },
    { title: "The Verge", desc: "Tech, science, art and culture.", url: "https://theverge.com" },
    { title: "Wired", desc: "The future of business, tech and culture.", url: "https://wired.com" },
    { title: "TechCrunch", desc: "Startup news and technology analysis.", url: "https://techcrunch.com" },
    { title: "Engadget", desc: "The original home for gadget news.", url: "https://engadget.com" },
    { title: "IGN", desc: "Everything for video games and movies.", url: "https://ign.com" },
    { title: "GameStar", desc: "Deutschlands größte PC-Spiele-Seite.", url: "https://gamestar.de" },
    { title: "Golem.de", desc: "IT-News für Profis.", url: "https://golem.de" },
    { title: "Scientific American", desc: "Science news and research.", url: "https://scientificamerican.com" },
    { title: "Nature", desc: "The leading international weekly journal of science.", url: "https://nature.com" },
    { title: "Kicker", desc: "Deutschlands Sportmagazin Nr. 1.", url: "https://kicker.de" },
    { title: "Sky Sport", desc: "Live-Sport und News.", url: "https://skysport.de" },
    { title: "ESPN", desc: "Global sports coverage.", url: "https://espn.com" },
    { title: "Vogue", desc: "Fashion, beauty and culture.", url: "https://vogue.com" },
    { title: "Rolling Stone", desc: "Music, politics and culture.", url: "https://rollingstone.com" },
    { title: "BZ Basel", desc: "Nachrichten aus der Region Basel.", url: "https://bzbasel.ch" },
    { title: "Berner Zeitung", desc: "News aus Bern und Umgebung.", url: "https://bernerzeitung.ch" },
    { title: "Luzerner Zeitung", desc: "Zentralschweizer Nachrichten.", url: "https://luzernerzeitung.ch" },
    { title: "St. Galler Tagblatt", desc: "Nachrichten aus der Ostschweiz.", url: "https://tagblatt.ch" },
    { title: "ProSieben", desc: "Entertainment und Serien.", url: "https://prosieben.de" },
    { title: "RTL News", desc: "Aktuelle News und Videos.", url: "https://rtl.de" },
    { title: "Arte", desc: "Der europäische Kultursender.", url: "https://arte.tv" },
    { title: "Euronews", desc: "Europäische Perspektiven auf Weltnachrichten.", url: "https://euronews.com" },
    { title: "Business Insider", desc: "Wirtschaftsnews für die junge Generation.", url: "https://businessinsider.de" },
    { title: "PC Welt", desc: "Tipps und News rund um den PC.", url: "https://pcwelt.de" },
    { title: "CHIP", desc: "Tests, Downloads und Technik-Ratgeber.", url: "https://chip.de" },
    { title: "Spektrum der Wissenschaft", desc: "Fundierte Berichte aus der Forschung.", url: "https://spektrum.de" },
    { title: "SBB CFF FFS", desc: "Die Bundesbahnen der Schweiz - Fahrplan und Tickets.", url: "https://sbb.ch" },
    { title: "ZVB", desc: "Zugerland Verkehrsbetriebe - Mobil im Kanton Zug.", url: "https://zvb.ch" },
    { title: "SOB", desc: "Schweizerische Südostbahn AG.", url: "https://sob.ch" },
    { title: "BLS", desc: "Die Verbindungen im Raum Bern und Lötschberg.", url: "https://bls.ch" },
    { title: "ZVV", desc: "Zürcher Verkehrsverbund - Alles für Zürich.", url: "https://zvv.ch" },
    { title: "PostAuto", desc: "Das gelbe Rückgrat des Schweizer Nahverkehrs.", url: "https://postauto.ch" },
    { title: "RhB", desc: "Rhätische Bahn - Weltkulturerbe in Graubünden.", url: "https://rhb.ch" },
    { title: "VBL", desc: "Verkehrsbetriebe Luzern.", url: "https://vbl.ch" },
    { title: "BVB", desc: "Basler Verkehrs-Betriebe.", url: "https://bvb.ch" },
    { title: "Bernmobil", desc: "Städtischer Verkehr in der Bundeshauptstadt.", url: "https://bernmobil.ch" },
    { title: "Tilo", desc: "Treni Regionali Ticino Lombardia.", url: "https://tilo.ch" },
    { title: "Zentralbahn", desc: "Die Bahnverbindung zwischen Luzern und Interlaken.", url: "https://zentralbahn.ch" },
    { title: "Appenzeller Bahnen", desc: "Unterwegs im Appenzellerland.", url: "https://appenzellerbahnen.ch" },
    { title: "MGBahn", desc: "Matterhorn Gotthard Bahn.", url: "https://mgbahn.ch" },
    { title: "Deutsche Bahn", desc: "Fahrplan und Buchung für Deutschland.", url: "https://bahn.de" },
    { title: "ÖBB", desc: "Österreichische Bundesbahnen.", url: "https://oebb.at" },
    { title: "FlixBus", desc: "Günstige Fernbusreisen in Europa.", url: "https://flixbus.de" },
    { title: "SNCF", desc: "Französische Staatsbahn.", url: "https://sncf.com" },
    { title: "Trenitalia", desc: "Bahnverkehr in Italien.", url: "https://trenitalia.com" },
    { title: "Eurostar", desc: "Der Zug durch den Kanaltunnel.", url: "https://eurostar.com" },
    { title: "Lufthansa", desc: "Größte deutsche Fluggesellschaft.", url: "https://lufthansa.com" },
    { title: "SWISS", desc: "Swiss International Air Lines.", url: "https://swiss.com" },
    { title: "Mobility", desc: "Carsharing in der ganzen Schweiz.", url: "https://mobility.ch" },
    { title: "PubliBike", desc: "Veloverleihsystem für Schweizer Städte.", url: "https://publibike.ch" },
    { title: "Uber", desc: "Fahrdienstvermittlung weltweit.", url: "https://uber.com" },
    { title: "Tesla", desc: "Elektromobilität und Innovation.", url: "https://tesla.com" },
    { title: "BlaBlaCar", desc: "Die größte Mitfahrzentrale.", url: "https://blablacar.de" },
    { title: "TCS", desc: "Touring Club Schweiz - Pannenhilfe und Infos.", url: "https://tcs.ch" },
    { title: "ADAC", desc: "Allgemeiner Deutscher Automobil-Club.", url: "https://adac.de" },
    { title: "Google Maps", desc: "Navigation und Verkehrslage in Echtzeit.", url: "https://maps.google.com" },
    { title: "Flightradar24", desc: "Flugzeuge weltweit live verfolgen.", url: "https://flightradar24.com" },
    { title: "MarineTraffic", desc: "Schiffsbewegungen weltweit in Echtzeit.", url: "https://marinetraffic.com" },
    { title: "Kanton Zug", desc: "Offizielle Webseite der Kantonsverwaltung.", url: "https://zg.ch" },
    { title: "Stadt Zug", desc: "Informationen und Dienste der Stadtverwaltung.", url: "https://stadtzug.ch" },
    { title: "Zuger Zeitung", desc: "Lokale Nachrichten aus dem Kanton Zug.", url: "https://zugerzeitung.ch" },
    { title: "Zentralplus Zug", desc: "Onlinemagazin für Zug und Luzern.", url: "https://zentralplus.ch/zug" },
    { title: "Zuger Kantonalbank", desc: "Die führende Bank in der Region.", url: "https://zugerkb.ch" },
    { title: "Wirtschaftsregion Zug", desc: "Infos zum Wirtschaftsstandort.", url: "https://zugwest.ch" },
    { title: "ZVB Zug", desc: "Zugerland Verkehrsbetriebe – Busse in der Region.", url: "https://zvb.ch" },
    { title: "Zugerberg Bahn", desc: "Standseilbahn auf den Zuger Hausberg.", url: "https://zbb.ch" },
    { title: "Schifffahrt Zugersee", desc: "Kursfahrten und Events auf dem Zugersee.", url: "https://zugersee-schifffahrt.ch" },
    { title: "Schifffahrt Ägerisee", desc: "Erholung auf dem Ägerisee.", url: "https://aegerisee-schifffahrt.ch" },
    { title: "Stadtbahn Zug", desc: "Informationen zum S-Bahn-Netz im Kanton.", url: "https://sbb.ch/stadtbahn-zug" },
    { title: "Ägerital-Sattel", desc: "Verkehrsbetriebe im Ägerital.", url: "https://aegerital-sattel.ch" },
    { title: "PH Zug", desc: "Pädagogische Hochschule Zug.", url: "https://phzg.ch" },
    { title: "Gewerblich-industrielle Berufsschule", desc: "GIBZ – Berufsbildung in Zug.", url: "https://gibz.ch" },
    { title: "Theater Casino Zug", desc: "Das kulturelle Zentrum der Stadt.", url: "https://theatercasino.ch" },
    { title: "Kunsthaus Zug", desc: "Moderne und zeitgenössische Kunst.", url: "https://kunsthauszug.ch" },
    { title: "Museum Burg Zug", desc: "Geschichte der Stadt und des Kantons.", url: "https://burgzug.ch" },
    { title: "Bibliothek Zug", desc: "Öffentliche Bibliothek der Stadt Zug.", url: "https://bibliothekzug.ch" },
    { title: "EV Zug", desc: "Eishockeyverein Zug - Offizielle Seite.", url: "https://evz.ch" },
    { title: "Zuger Messe", desc: "Die größte Herbstmesse der Zentralschweiz.", url: "https://zugermesse.ch" },
    { title: "Höllgrotten Baar", desc: "Einzigartige Tropfsteinhöhlen in der Nähe.", url: "https://hoellgrotten.ch" },
    { title: "Zugerland Einkaufszentrum", desc: "Shopping in Steinhausen.", url: "https://ekz-zugerland.ch" },
    { title: "Rigi Bahnen", desc: "Die Königin der Berge direkt ab Arth-Goldau.", url: "https://rigi.ch" },
    { title: "Pilatus Bahnen", desc: "Steilste Zahnradbahn der Welt.", url: "https://pilatus.ch" },
    { title: "Sattel-Hochstuckli", desc: "Familienberg im Kanton Schwyz (nah bei Zug).", url: "https://sattel-hochstuckli.ch" },
    { title: "NASA", desc: "National Aeronautics and Space Administration.", url: "https://nasa.gov" },
    { title: "ESA", desc: "European Space Agency - Europas Tor zum Weltraum.", url: "https://esa.int" },
    { title: "DLR", desc: "Deutsches Zentrum für Luft- und Raumfahrt.", url: "https://dlr.de" },
    { title: "JAXA", desc: "Japan Aerospace Exploration Agency.", url: "https://jaxa.jp" },
    { title: "CSA", desc: "Canadian Space Agency.", url: "https://asc-csa.gc.ca" },
    { title: "Swiss Space Office", desc: "Schweizer Raumfahrtaktivitäten (SBFI).", url: "https://sbfi.admin.ch/space" },
    { title: "Roscosmos", desc: "Staatliche russische Weltraumorganisation.", url: "https://roscosmos.ru" },
    { title: "SpaceX", desc: "Wiederverwendbare Raketen und Mars-Missionen.", url: "https://spacex.com" },
    { title: "Blue Origin", desc: "Jeff Bezos' Vision für die Raumfahrt.", url: "https://blueorigin.com" },
    { title: "Virgin Galactic", desc: "Kommerzielle suborbitale Raumflüge.", url: "https://virgingalactic.com" },
    { title: "Rocket Lab", desc: "Spezialist für kleine Satellitenstarts.", url: "https://rocketlabusa.com" },
    { title: "Sierra Space", desc: "Entwickler des Dream Chaser Raumgleiters.", url: "https://sierraspace.com" },
    { title: "Arianespace", desc: "Europäischer Marktführer für Satellitenstarts.", url: "https://arianespace.com" },
    { title: "Space.com", desc: "Nachrichten über Astronomie und Exploration.", url: "https://space.com" },
    { title: "NASA Image of the Day", desc: "Täglich beeindruckende Bilder aus dem All.", url: "https://apod.nasa.gov/apod" },
    { title: "SpaceFlight Now", desc: "Live-Berichterstattung von Raketenstarts.", url: "https://spaceflightnow.com" },
    { title: "Universe Today", desc: "Hintergründe zu Astronomie und Kosmologie.", url: "https://universetoday.com" },
    { title: "Sky & Telescope", desc: "Das Magazin für Hobby-Astronomen.", url: "https://skyandtelescope.org" },
    { title: "Hubble Site", desc: "Bilder und Entdeckungen des Hubble-Teleskops.", url: "https://hubblesite.org" },
    { title: "James Webb Tracker", desc: "Status und Bilder des JWST.", url: "https://webb.nasa.gov" },
    { title: "Heavens-Above", desc: "Satelliten und die ISS am Himmel finden.", url: "https://heavens-above.com" },
    { title: "Stellarium Web", desc: "Der Sternenhimmel live im Browser.", url: "https://stellarium-web.org" },
    { title: "Eyes on the Solar System", desc: "Echtzeit-Simulation des Sonnensystems durch die NASA.", url: "https://eyes.nasa.gov" },
    { title: "ISS Tracker", desc: "Wo befindet sich die Raumstation gerade?", url: "https://iss-tracker.org" },
    { title: "Space Weather Prediction", desc: "Infos zu Sonnenstürmen und Polarlichtern.", url: "https://swpc.noaa.gov" },
    { title: "Verkehrshaus Schweiz", desc: "Große Raumfahrt-Ausstellung in Luzern.", url: "https://verkehrshaus.ch" },
    { title: "Smithsonian Air and Space", desc: "Das berühmteste Luftfahrtmuseum der Welt.", url: "https://airandspace.si.edu" }
];
