// favoriten.js
const meineLieblingsSeiten = [
    { title: "Glaggle", desc: "Glaggle Your life!", url: "https://glaggle.ch" },
    { title: "YouTube", desc: "Schaue die neuesten Videos weltweit.", url: "https://youtube.com" },
    { title: "Glaggle Zahlenraten", desc: "Ein lustiges Spiel, um Zahlen zu erraten.", url: "https://glaggle.ch/zahlenraten" },
    { title: "Glame AI", desc: "Nutze den intelligenten KI Chatbot von Glaggle", url: "https://glaggle.ch/glame" },
    { title: "Glaggle Mail", desc: "Sichere E-Mails für dein Glaggle-Konto.", url: "https://mail.glaggle.ch" },
    { title: "Facebook", desc: "Vernetze dich mit Freunden und der Welt.", url: "https://facebook.com" },
    { title: "Instagram", desc: "Teile Fotos und Videos mit deinen Followern.", url: "https://instagram.com" },
    { title: "TikTok", desc: "Kurzvideos, die Trends setzen.", url: "https://tiktok.com" },
    { title: "X (Twitter)", desc: "Echtzeit-Nachrichten und Diskussionen.", url: "https://x.com" },
    { title: "LinkedIn", desc: "Das Netzwerk für berufliche Kontakte.", url: "https://linkedin.com" },
    { title: "Reddit", desc: "Die Startseite des Internets für Foren.", url: "https://reddit.com" },
    { title: "Pinterest", desc: "Entdecke Rezepte, Deko-Ideen und Inspiration.", url: "https://pinterest.com" },
    { title: "Discord", desc: "Chatten und Communities für Gamer und Creator.", url: "https://discord.com" },
    { title: "WhatsApp", desc: "Messenger für Text und Telefonie.", url: "https://web.whatsapp.com" },
    { title: "Telegram", desc: "Sicherer Cloud-basierter Messenger.", url: "https://telegram.org" },
    { title: "Wikipedia", desc: "Die freie Enzyklopädie.", url: "https://wikipedia.org" },
    { title: "Google Maps", desc: "Finde Routen und Orte weltweit.", url: "https://maps.google.com" },
    { title: "DeepL", desc: "Der präziseste Übersetzer der Welt.", url: "https://deepl.com" },
    { title: "Quora", desc: "Fragen stellen und Wissen teilen.", url: "https://quora.com" },
    { title: "Stack Overflow", desc: "Die größte Community für Programmierer.", url: "https://stackoverflow.com" },
    { title: "GitHub", desc: "Hoste und verwalte deinen Code.", url: "https://github.com" },
    { title: "Medium", desc: "Plattform für tiefgründige Artikel und Blogs.", url: "https://medium.com" },
    { title: "Amazon", desc: "Alles finden, vergleichen und kaufen.", url: "https://amazon.de" },
    { title: "eBay", desc: "Kaufen und Verkaufen von Neu- und Gebrauchtware.", url: "https://ebay.de" },
    { title: "Etsy", desc: "Handgemachtes, Vintage und Kreatives.", url: "https://etsy.com" },
    { title: "AliExpress", desc: "Globaler Marktplatz für günstige Produkte.", url: "https://aliexpress.com" },
    { title: "Netflix", desc: "Serien und Filme online streamen.", url: "https://netflix.com" },
    { title: "Twitch", desc: "Live-Streaming von Games und Entertainment.", url: "https://twitch.tv" },
    { title: "Spotify", desc: "Millionen von Songs und Podcasts.", url: "https://spotify.com" },
    { title: "Disney+", desc: "Die Heimat von Disney, Pixar und Marvel.", url: "https://disneyplus.com" },
    { title: "Steam", desc: "Die ultimative Plattform für PC-Spiele.", url: "https://steampowered.com" },
    { title: "SRF", desc: "Schweizer Radio und Fernsehen - News und Unterhaltung.", url: "https://srf.ch" },
    { title: "NZZ", desc: "Neue Zürcher Zeitung - Hochwertiger Journalismus.", url: "https://nzz.ch" },
    { title: "Tages-Anzeiger", desc: "Aktuelle Nachrichten aus Zürich und der Welt.", url: "https://tagesanzeiger.ch" },
    { title: "20 Minuten", desc: "Die meistgelesene Gratiszeitung der Schweiz.", url: "https://20min.ch" },
    { title: "Blick", desc: "Nachrichten, Sport und People-News.", url: "https://blick.ch" },
    { title: "Watson", desc: "News, Unterhaltung und Debatten für die Schweiz.", url: "https://watson.ch" },
    { title: "RTS", desc: "Radio Télévision Suisse - Westschweizer Rundfunk.", url: "https://rts.ch" },
    { title: "Tagesschau", desc: "Deutschlands wichtigste Nachrichtensendung.", url: "https://tagesschau.de" },
    { title: "ZDF heute", desc: "Nachrichten des Zweiten Deutschen Fernsehens.", url: "https://zdf.de/nachrichten" },
    { title: "Der Spiegel", desc: "Investigativer Journalismus und aktuelle News.", url: "https://spiegel.de" },
    { title: "Die Zeit", desc: "Analysen, Hintergründe und Politik.", url: "https://zeit.de" },
    { title: "ORF", desc: "Österreichischer Rundfunk - News und TV.", url: "https://orf.at" },
    { title: "Der Standard", desc: "Qualitätsjournalismus aus Österreich.", url: "https://derstandard.at" },
    { title: "Süddeutsche Zeitung", desc: "Überregionale Tageszeitung aus München.", url: "https://sueddeutsche.de" },
    { title: "FAZ", desc: "Frankfurter Allgemeine Zeitung.", url: "https://faz.net" },
    { title: "Handelsblatt", desc: "Wirtschafts- und Finanznachrichten.", url: "https://handelsblatt.com" },
    { title: "BBC News", desc: "World news and international analysis.", url: "https://bbc.com/news" },
    { title: "CNN", desc: "Breaking news and video from around the world.", url: "https://cnn.com" },
    { title: "The New York Times", desc: "International and US news, opinion and culture.", url: "https://nytimes.com" },
    { title: "The Guardian", desc: "Independent world news and liberal opinion.", url: "https://theguardian.com" },
    { title: "Reuters", desc: "Global news agency for business and politics.", url: "https://reuters.com" },
    { title: "Associated Press", desc: "Independent news from every corner of the globe.", url: "https://apnews.com" },
    { title: "Al Jazeera", desc: "Breaking news and analysis from the Middle East.", url: "https://aljazeera.com" },
    { title: "The Wall Street Journal", desc: "Business and stock market news.", url: "https://wsj.com" },
    { title: "Bloomberg", desc: "Global business and financial data.", url: "https://bloomberg.com" },
    { title: "The Economist", desc: "World politics, business and finance.", url: "https://economist.com" },
    { title: "TIME", desc: "Politics, history and world events.", url: "https://time.com" },
    { title: "National Geographic", desc: "Science, nature and exploration.", url: "https://nationalgeographic.com" },
    { title: "The Washington Post", desc: "Democracy dies in darkness.", url: "https://washingtonpost.com" },
    { title: "Forbes", desc: "Business, technology and leadership.", url: "https://forbes.com" },
    { title: "Heise Online", desc: "IT-News und Hintergründe aus Deutschland.", url: "https://heise.de" },
    { title: "The Verge", desc: "Tech, science, art and culture.", url: "https://theverge.com" },
    { title: "Wired", desc: "The future of business, tech and culture.", url: "https://wired.com" },
    { title: "TechCrunch", desc: "Startup news and technology analysis.", url: "https://techcrunch.com" },
    { title: "Engadget", desc: "The original home for gadget news.", url: "https://engadget.com" },
    { title: "IGN", desc: "Everything for video games and movies.", url: "https://ign.com" },
    { title: "GameStar", desc: "Deutschlands größte PC-Spiele-Seite.", url: "https://gamestar.de" },
    { title: "Golem.de", desc: "IT-News für Profis.", url: "https://golem.de" },
    { title: "Scientific American", desc: "Science news and research.", url: "https://scientificamerican.com" },
    { title: "Nature", desc: "The leading international weekly journal of science.", url: "https://nature.com" },
    { title: "Kicker", desc: "Deutschlands Sportmagazin Nr. 1.", url: "https://kicker.de" },
    { title: "Sky Sport", desc: "Live-Sport und News.", url: "https://skysport.de" },
    { title: "ESPN", desc: "Global sports coverage.", url: "https://espn.com" },
    { title: "Vogue", desc: "Fashion, beauty and culture.", url: "https://vogue.com" },
    { title: "Rolling Stone", desc: "Music, politics and culture.", url: "https://rollingstone.com" },
    { title: "BZ Basel", desc: "Nachrichten aus der Region Basel.", url: "https://bzbasel.ch" },
    { title: "Berner Zeitung", desc: "News aus Bern und Umgebung.", url: "https://bernerzeitung.ch" },
    { title: "Luzerner Zeitung", desc: "Zentralschweizer Nachrichten.", url: "https://luzernerzeitung.ch" },
    { title: "St. Galler Tagblatt", desc: "Nachrichten aus der Ostschweiz.", url: "https://tagblatt.ch" },
    { title: "ProSieben", desc: "Entertainment und Serien.", url: "https://prosieben.de" },
    { title: "RTL News", desc: "Aktuelle News und Videos.", url: "https://rtl.de" },
    { title: "Arte", desc: "Der europäische Kultursender.", url: "https://arte.tv" },
    { title: "Euronews", desc: "Europäische Perspektiven auf Weltnachrichten.", url: "https://euronews.com" },
    { title: "Business Insider", desc: "Wirtschaftsnews für die junge Generation.", url: "https://businessinsider.de" },
    { title: "PC Welt", desc: "Tipps und News rund um den PC.", url: "https://pcwelt.de" },
    { title: "CHIP", desc: "Tests, Downloads und Technik-Ratgeber.", url: "https://chip.de" },
    { title: "Spektrum der Wissenschaft", desc: "Fundierte Berichte aus der Forschung.", url: "https://spektrum.de" },
    { title: "SBB CFF FFS", desc: "Die Bundesbahnen der Schweiz - Fahrplan und Tickets.", url: "https://sbb.ch" },
    { title: "ZVB", desc: "Zugerland Verkehrsbetriebe - Mobil im Kanton Zug.", url: "https://zvb.ch" },
    { title: "SOB", desc: "Schweizerische Südostbahn AG.", url: "https://sob.ch" },
    { title: "BLS", desc: "Die Verbindungen im Raum Bern und Lötschberg.", url: "https://bls.ch" },
    { title: "ZVV", desc: "Zürcher Verkehrsverbund - Alles für Zürich.", url: "https://zvv.ch" },
    { title: "PostAuto", desc: "Das gelbe Rückgrat des Schweizer Nahverkehrs.", url: "https://postauto.ch" },
    { title: "RhB", desc: "Rhätische Bahn - Weltkulturerbe in Graubünden.", url: "https://rhb.ch" },
    { title: "VBL", desc: "Verkehrsbetriebe Luzern.", url: "https://vbl.ch" },
    { title: "BVB", desc: "Basler Verkehrs-Betriebe.", url: "https://bvb.ch" },
    { title: "Bernmobil", desc: "Städtischer Verkehr in der Bundeshauptstadt.", url: "https://bernmobil.ch" },
    { title: "Tilo", desc: "Treni Regionali Ticino Lombardia.", url: "https://tilo.ch" },
    { title: "Zentralbahn", desc: "Die Bahnverbindung zwischen Luzern und Interlaken.", url: "https://zentralbahn.ch" },
    { title: "Appenzeller Bahnen", desc: "Unterwegs im Appenzellerland.", url: "https://appenzellerbahnen.ch" },
    { title: "MGBahn", desc: "Matterhorn Gotthard Bahn.", url: "https://mgbahn.ch" },
    { title: "Deutsche Bahn", desc: "Fahrplan und Buchung für Deutschland.", url: "https://bahn.de" },
    { title: "ÖBB", desc: "Österreichische Bundesbahnen.", url: "https://oebb.at" },
    { title: "FlixBus", desc: "Günstige Fernbusreisen in Europa.", url: "https://flixbus.de" },
    { title: "SNCF", desc: "Französische Staatsbahn.", url: "https://sncf.com" },
    { title: "Trenitalia", desc: "Bahnverkehr in Italien.", url: "https://trenitalia.com" },
    { title: "Eurostar", desc: "Der Zug durch den Kanaltunnel.", url: "https://eurostar.com" },
    { title: "Lufthansa", desc: "Größte deutsche Fluggesellschaft.", url: "https://lufthansa.com" },
    { title: "SWISS", desc: "Swiss International Air Lines.", url: "https://swiss.com" },
    { title: "Mobility", desc: "Carsharing in der ganzen Schweiz.", url: "https://mobility.ch" },
    { title: "PubliBike", desc: "Veloverleihsystem für Schweizer Städte.", url: "https://publibike.ch" },
    { title: "Uber", desc: "Fahrdienstvermittlung weltweit.", url: "https://uber.com" },
    { title: "Tesla", desc: "Elektromobilität und Innovation.", url: "https://tesla.com" },
    { title: "BlaBlaCar", desc: "Die größte Mitfahrzentrale.", url: "https://blablacar.de" },
    { title: "TCS", desc: "Touring Club Schweiz - Pannenhilfe und Infos.", url: "https://tcs.ch" },
    { title: "ADAC", desc: "Allgemeiner Deutscher Automobil-Club.", url: "https://adac.de" },
    { title: "Google Maps", desc: "Navigation und Verkehrslage in Echtzeit.", url: "https://maps.google.com" },
    { title: "Flightradar24", desc: "Flugzeuge weltweit live verfolgen.", url: "https://flightradar24.com" },
    { title: "MarineTraffic", desc: "Schiffsbewegungen weltweit in Echtzeit.", url: "https://marinetraffic.com" },
    { title: "Kanton Zug", desc: "Offizielle Webseite der Kantonsverwaltung.", url: "https://zg.ch" },
    { title: "Stadt Zug", desc: "Informationen und Dienste der Stadtverwaltung.", url: "https://stadtzug.ch" },
    { title: "Zuger Zeitung", desc: "Lokale Nachrichten aus dem Kanton Zug.", url: "https://zugerzeitung.ch" },
    { title: "Zentralplus Zug", desc: "Onlinemagazin für Zug und Luzern.", url: "https://zentralplus.ch/zug" },
    { title: "Zuger Kantonalbank", desc: "Die führende Bank in der Region.", url: "https://zugerkb.ch" },
    { title: "Wirtschaftsregion Zug", desc: "Infos zum Wirtschaftsstandort.", url: "https://zugwest.ch" },
    { title: "ZVB Zug", desc: "Zugerland Verkehrsbetriebe – Busse in der Region.", url: "https://zvb.ch" },
    { title: "Zugerberg Bahn", desc: "Standseilbahn auf den Zuger Hausberg.", url: "https://zbb.ch" },
    { title: "Schifffahrt Zugersee", desc: "Kursfahrten und Events auf dem Zugersee.", url: "https://zugersee-schifffahrt.ch" },
    { title: "Schifffahrt Ägerisee", desc: "Erholung auf dem Ägerisee.", url: "https://aegerisee-schifffahrt.ch" },
    { title: "Stadtbahn Zug", desc: "Informationen zum S-Bahn-Netz im Kanton.", url: "https://sbb.ch/stadtbahn-zug" },
    { title: "Ägerital-Sattel", desc: "Verkehrsbetriebe im Ägerital.", url: "https://aegerital-sattel.ch" },
    { title: "PH Zug", desc: "Pädagogische Hochschule Zug.", url: "https://phzg.ch" },
    { title: "Gewerblich-industrielle Berufsschule", desc: "GIBZ – Berufsbildung in Zug.", url: "https://gibz.ch" },
    { title: "Theater Casino Zug", desc: "Das kulturelle Zentrum der Stadt.", url: "https://theatercasino.ch" },
    { title: "Kunsthaus Zug", desc: "Moderne und zeitgenössische Kunst.", url: "https://kunsthauszug.ch" },
    { title: "Museum Burg Zug", desc: "Geschichte der Stadt und des Kantons.", url: "https://burgzug.ch" },
    { title: "Bibliothek Zug", desc: "Öffentliche Bibliothek der Stadt Zug.", url: "https://bibliothekzug.ch" },
    { title: "EV Zug", desc: "Eishockeyverein Zug - Offizielle Seite.", url: "https://evz.ch" },
    { title: "Zuger Messe", desc: "Die größte Herbstmesse der Zentralschweiz.", url: "https://zugermesse.ch" },
    { title: "Höllgrotten Baar", desc: "Einzigartige Tropfsteinhöhlen in der Nähe.", url: "https://hoellgrotten.ch" },
    { title: "Zugerland Einkaufszentrum", desc: "Shopping in Steinhausen.", url: "https://ekz-zugerland.ch" },
    { title: "Rigi Bahnen", desc: "Die Königin der Berge direkt ab Arth-Goldau.", url: "https://rigi.ch" },
    { title: "Pilatus Bahnen", desc: "Steilste Zahnradbahn der Welt.", url: "https://pilatus.ch" },
    { title: "Sattel-Hochstuckli", desc: "Familienberg im Kanton Schwyz (nah bei Zug).", url: "https://sattel-hochstuckli.ch" },
    { title: "NASA", desc: "National Aeronautics and Space Administration.", url: "https://nasa.gov" },
    { title: "ESA", desc: "European Space Agency - Europas Tor zum Weltraum.", url: "https://esa.int" },
    { title: "DLR", desc: "Deutsches Zentrum für Luft- und Raumfahrt.", url: "https://dlr.de" },
    { title: "JAXA", desc: "Japan Aerospace Exploration Agency.", url: "https://jaxa.jp" },
    { title: "CSA", desc: "Canadian Space Agency.", url: "https://asc-csa.gc.ca" },
    { title: "Swiss Space Office", desc: "Schweizer Raumfahrtaktivitäten (SBFI).", url: "https://sbfi.admin.ch/space" },
    { title: "Roscosmos", desc: "Staatliche russische Weltraumorganisation.", url: "https://roscosmos.ru" },
    { title: "SpaceX", desc: "Wiederverwendbare Raketen und Mars-Missionen.", url: "https://spacex.com" },
    { title: "Blue Origin", desc: "Jeff Bezos' Vision für die Raumfahrt.", url: "https://blueorigin.com" },
    { title: "Virgin Galactic", desc: "Kommerzielle suborbitale Raumflüge.", url: "https://virgingalactic.com" },
    { title: "Rocket Lab", desc: "Spezialist für kleine Satellitenstarts.", url: "https://rocketlabusa.com" },
    { title: "Sierra Space", desc: "Entwickler des Dream Chaser Raumgleiters.", url: "https://sierraspace.com" },
    { title: "Arianespace", desc: "Europäischer Marktführer für Satellitenstarts.", url: "https://arianespace.com" },
    { title: "Space.com", desc: "Nachrichten über Astronomie und Exploration.", url: "https://space.com" },
    { title: "NASA Image of the Day", desc: "Täglich beeindruckende Bilder aus dem All.", url: "https://apod.nasa.gov/apod" },
    { title: "SpaceFlight Now", desc: "Live-Berichterstattung von Raketenstarts.", url: "https://spaceflightnow.com" },
    { title: "Universe Today", desc: "Hintergründe zu Astronomie und Kosmologie.", url: "https://universetoday.com" },
    { title: "Sky & Telescope", desc: "Das Magazin für Hobby-Astronomen.", url: "https://skyandtelescope.org" },
    { title: "Hubble Site", desc: "Bilder und Entdeckungen des Hubble-Teleskops.", url: "https://hubblesite.org" },
    { title: "James Webb Tracker", desc: "Status und Bilder des JWST.", url: "https://webb.nasa.gov" },
    { title: "Heavens-Above", desc: "Satelliten und die ISS am Himmel finden.", url: "https://heavens-above.com" },
    { title: "Stellarium Web", desc: "Der Sternenhimmel live im Browser.", url: "https://stellarium-web.org" },
    { title: "Eyes on the Solar System", desc: "Echtzeit-Simulation des Sonnensystems durch die NASA.", url: "https://eyes.nasa.gov" },
    { title: "ISS Tracker", desc: "Wo befindet sich die Raumstation gerade?", url: "https://iss-tracker.org" },
    { title: "Space Weather Prediction", desc: "Infos zu Sonnenstürmen und Polarlichtern.", url: "https://swpc.noaa.gov" },
    { title: "Verkehrshaus Schweiz", desc: "Große Raumfahrt-Ausstellung in Luzern.", url: "https://verkehrshaus.ch" },
    { title: "Smithsonian Air and Space", desc: "Das berühmteste Luftfahrtmuseum der Welt.", url: "https://airandspace.si.edu" },
    { title: "IGN", desc: "Weltweite Nummer 1 für Game-Reviews und Trailer.", url: "https://ign.com" },
    { title: "GameStar", desc: "Größte deutsche PC-Gaming-Plattform.", url: "https://gamestar.de" },
    { title: "Eurogamer", desc: "Kritische Analysen und europäische Gaming-News.", url: "https://eurogamer.net" },
    { title: "Kotaku", desc: "Gaming-Kultur, News und Kurioses.", url: "https://kotaku.com" },
    { title: "GameSpot", desc: "Umfangreiche Video-Reviews und Guides.", url: "https://gamespot.com" },
    { title: "PC Gamer", desc: "Alles rund um PC-Hardware und Spiele.", url: "https://pcgamer.com" },
    { title: "Polygon", desc: "Gaming-Journalismus mit Fokus auf Storytelling.", url: "https://polygon.com" },
    { title: "Rock Paper Shotgun", desc: "Der Spezialist für PC-Spiele und Indie-Titel.", url: "https://rockpapershotgun.com" },
    { title: "VGC", desc: "Video Games Chronicle - Insider-News der Industrie.", url: "https://videogameschronicle.com" },
    { title: "Steam", desc: "Die größte Plattform für PC-Spiele weltweit.", url: "https://steampowered.com" },
    { title: "Epic Games Store", desc: "Home of Fortnite und wöchentliche Gratis-Spiele.", url: "https://epicgames.com" },
    { title: "GOG.com", desc: "Good Old Games - Klassiker ohne Kopierschutz.", url: "https://gog.com" },
    { title: "Nintendo", desc: "Offizielle Seite von Mario, Zelda und der Switch.", url: "https://nintendo.ch" },
    { title: "PlayStation", desc: "Alles zur PS5 und dem PS Plus Service.", url: "https://playstation.com" },
    { title: "Xbox", desc: "Microsofts Gaming-Sparte und Game Pass.", url: "https://xbox.com" },
    { title: "Itch.io", desc: "Die Heimat für kreative Indie-Games.", url: "https://itch.io" },
    { title: "Twitch", desc: "Die führende Plattform für Live-Streaming.", url: "https://twitch.tv" },
    { title: "HLTV", desc: "Die wichtigste Seite für Counter-Strike E-Sport.", url: "https://hltv.org" },
    { title: "Liquipedia", desc: "Das Wiki für alle E-Sport-Disziplinen.", url: "https://liquipedia.net" },
    { title: "ESL Faceit", desc: "Weltweiter Marktführer für E-Sport-Turniere.", url: "https://eslfaceit.com" },
    { title: "Dotabuff", desc: "Detaillierte Statistiken für Dota 2.", url: "https://dotabuff.com" },
    { title: "Metacritic", desc: "Bewertungsspiegel für Filme und Spiele.", url: "https://metacritic.com" },
    { title: "HowLongToBeat", desc: "Finde heraus, wie lange man für ein Spiel braucht.", url: "https://howlongtobeat.com" },
    { title: "Nexus Mods", desc: "Die größte Modding-Community im Web.", url: "https://nexusmods.com" },
    { title: "Speedrun.com", desc: "Weltrekorde und Bestenlisten für Speedrunner.", url: "https://speedrun.com" },
    { title: "PCPartPicker", desc: "Plane deinen Gaming-PC und prüfe Kompatibilität.", url: "https://pcpartpicker.com" },
    { title: "Discord", desc: "Chat-Plattform für Gamer und Communities.", url: "https://discord.com" },
    { title: "Unity", desc: "Beliebte Engine für Indie- und Mobile-Games.", url: "https://unity.com" },
    { title: "Unreal Engine", desc: "Die Grafik-Power hinter AAA-Titeln.", url: "https://unrealengine.com" },
    { title: "Roblox", desc: "Spieleplattform und Baukasten für Creator.", url: "https://roblox.com" },
    { title: "Blender", desc: "Die beste Open-Source-Suite für 3D-Erstellung.", url: "https://blender.org" },
    { title: "GIMP", desc: "Die freie Alternative zu Photoshop.", url: "https://gimp.org" },
    { title: "Krita", desc: "Professionelles, freies Malprogramm für Künstler.", url: "https://krita.org" },
    { title: "Inkscape", desc: "Vektorgrafiken professionell erstellen.", url: "https://inkscape.org" },
    { title: "Darktable", desc: "Open-Source-Fotoworkflow und RAW-Entwicklung.", url: "https://darktable.org" },
    { title: "Scribus", desc: "Desktop Publishing (DTP) als Open Source.", url: "https://scribus.net" },
    { title: "FreeCAD", desc: "Ein parametrischer 3D-CAD-Modellierer.", url: "https://freecad.org" },
    { title: "OBS Studio", desc: "Software für Videoaufnahme und Live-Streaming.", url: "https://obsproject.com" },
    { title: "HandBrake", desc: "Open-Source-Video-Transcoder für jedes Format.", url: "https://handbrake.fr" },
    { title: "Audacity", desc: "Der Standard für freie Audiobearbeitung.", url: "https://audacityteam.org" },
    { title: "VLC Media Player", desc: "Spielt einfach jedes Videoformat ab.", url: "https://videolan.org" },
    { title: "Shotcut", desc: "Ein freier, quelloffener Video-Editor.", url: "https://shotcut.org" },
    { title: "Kdenlive", desc: "Leistungsstarker Video-Editor für Linux und Windows.", url: "https://kdenlive.org" },
    { title: "LibreOffice", desc: "Die freie Office-Suite für Text, Tabellen und Präsentationen.", url: "https://libreoffice.org" },
    { title: "7-Zip", desc: "Packprogramm mit hoher Kompressionsrate.", url: "https://7-zip.org" },
    { title: "Notepad++", desc: "Extrem schneller Editor für Code und Text.", url: "https://notepad-plus-plus.org" },
    { title: "Thunderbird", desc: "Sicherer und freier E-Mail-Client von Mozilla.", url: "https://thunderbird.net" },
    { title: "Bitwarden", desc: "Open-Source-Passwortmanager für alle Geräte.", url: "https://bitwarden.com" },
    { title: "Linux Mint", desc: "Eine der benutzerfreundlichsten Linux-Distributionen.", url: "https://linuxmint.com" },
    { title: "Ubuntu", desc: "Das weltweit meistgenutzte Linux-Betriebssystem.", url: "https://ubuntu.com" },
    { title: "Visual Studio Code", desc: "Der mächtige Code-Editor von Microsoft (Open Source Basis).", url: "https://code.visualstudio.com" },
    { title: "Python", desc: "Die vielseitigste Programmiersprache unserer Zeit.", url: "https://python.org" },
    { title: "WordPress.org", desc: "Die Software, die das halbe Web antreibt.", url: "https://wordpress.org" },
    { title: "Mozilla Firefox", desc: "Der Browser, der Privatsphäre ernst nimmt.", url: "https://firefox.com" },
    { title: "Nextcloud", desc: "Die selbstgehostete Cloud-Alternative.", url: "https://nextcloud.com" },// --- DESIGN & KREATIVITÄT (WEB-BASIERT) ---
    { title: "Canva", desc: "Design-Plattform für Grafiken, Social Media und Präsentationen.", url: "https://canva.com" },
    { title: "Figma", desc: "Das führende Tool für UI/UX-Design und Prototyping.", url: "https://figma.com" },
    { title: "Adobe Express", desc: "Schnelle Design-Tools von den Machern von Photoshop.", url: "https://adobe.com/express" },
    { title: "Behance", desc: "Portfolio-Plattform zur Präsentation kreativer Arbeiten.", url: "https://behance.net" },
    { title: "Dribbble", desc: "Inspiration und Community für Designer.", url: "https://dribbble.com" },
    { title: "Photopea", desc: "Kostenlose Photoshop-Alternative direkt im Browser.", url: "https://photopea.com" },
    { title: "Pinterest", desc: "Visuelle Entdeckungsreise für Ideen und Inspiration.", url: "https://pinterest.com" },
    { title: "Microsoft 365 / Word", desc: "Textverarbeitung und Cloud-Office von Microsoft.", url: "https://office.com" },
    { title: "Google Docs", desc: "Kollaborative Textverarbeitung im Web.", url: "https://docs.google.com" },
    { title: "Notion", desc: "All-in-One-Workspace für Notizen, Aufgaben und Datenbanken.", url: "https://notion.so" },
    { title: "Trello", desc: "Projektmanagement mit übersichtlichen Kanban-Boards.", url: "https://trello.com" },
    { title: "Asana", desc: "Plattform für Team-Management und Arbeitsabläufe.", url: "https://asana.com" },
    { title: "Slack", desc: "Die zentrale Plattform für Team-Kommunikation.", url: "https://slack.com" },
    { title: "Zoom", desc: "Videokonferenzen und Online-Meetings.", url: "https://zoom.us" },
    { title: "Miro", desc: "Virtuelle Whiteboards für visuelle Zusammenarbeit.", url: "https://miro.com" },
    { title: "Dropbox", desc: "Einfacher Cloud-Speicher und Dateiaustausch.", url: "https://dropbox.com" },
    { title: "WeTransfer", desc: "Der schnellste Weg, um große Dateien zu versenden.", url: "https://wetransfer.com" },
    { title: "Google Drive", desc: "Sicherer Cloud-Speicher für alle Dateitypen.", url: "https://drive.google.com" },
    { title: "iCloud", desc: "Apples Cloud-Dienst für Fotos, Dokumente und Backups.", url: "https://icloud.com" },
    { title: "ChatGPT", desc: "Fortschrittliche KI für Texte, Code und Analysen.", url: "https://chatgpt.com" },
    { title: "Claude AI", desc: "Intelligente Sprach-KI von Anthropic.", url: "https://claude.ai" },
    { title: "Perplexity AI", desc: "KI-gestützte Suchmaschine für präzise Antworten.", url: "https://perplexity.ai" },
    { title: "DeepL Write", desc: "KI-Tool zur Verbesserung von Grammatik und Stil.", url: "https://deepl.com/write" },
    { title: "Pixabay", desc: "Über 4 Millionen hochwertige Stock-Fotos, Videos und Musik.", url: "https://pixabay.com" },
    { title: "Pexels", desc: "Die besten kostenlosen Stock-Fotos und Videos an einem Ort.", url: "https://pexels.com" },
    { title: "Unsplash", desc: "Wunderschöne, kostenlose Bilder von der weltweiten Fotografen-Community.", url: "https://unsplash.com" },
    { title: "Freepik", desc: "Grafikressourcen wie Vektoren, Fotos und PSD-Dateien.", url: "https://freepik.com" },
    { title: "Burst", desc: "Kostenlose Stock-Fotos für Websites und kommerzielle Nutzung.", url: "https://burst.shopify.com" },
    { title: "StockSnap.io", desc: "Hundertausende hochauflösende Bilder ohne Copyright-Beschränkungen.", url: "https://stocksnap.io" },
    { title: "Flaticon", desc: "Die größte Datenbank für kostenlose Icons im Web.", url: "https://flaticon.com" },
    { title: "Font Awesome", desc: "Die beliebteste Icon-Library für Webentwickler.", url: "https://fontawesome.com" },
    { title: "Iconfinder", desc: "Millionen von Icons für Designer und Entwickler.", url: "https://iconfinder.com" },
    { title: "Noun Project", desc: "Icons und Fotos für absolut alles.", url: "https://thenounproject.com" },
    { title: "Free Music Archive", desc: "Kostenlose Musik für Videos und Projekte.", url: "https://freemusicarchive.org" },
    { title: "Bensound", desc: "Gebührenfreie Musik für YouTube und Multimedia.", url: "https://bensound.com" },
    { title: "Epidemic Sound", desc: "Professionelle Musik und Soundeffekte (Abo-Modell).", url: "https://epidemicsound.com" },
    { title: "Google Fonts", desc: "Kostenlose Schriftarten für Web und Print.", url: "https://fonts.google.com" },
    { title: "Adobe Color", desc: "Farbenräder erstellen und Farbschemata entdecken.", url: "https://color.adobe.com" },
    { title: "Coolors", desc: "Der superschnelle Farbschema-Generator.", url: "https://coolors.co" },
    { title: "Dafont", desc: "Riesiges Archiv für ausgefallene Gratis-Schriftarten.", url: "https://dafont.com" },
    { title: "Coolors", desc: "Der superschnelle Farbschema-Generator.", url: "https://coolors.co" },
    { title: "Dafont", desc: "Riesiges Archiv für ausgefallene Gratis-Schriftarten.", url: "https://dafont.com" },
    // --- BILDUNG & ONLINE-KURSE ---
{ title: "Coursera", desc: "Online-Kurse von Universitäten weltweit.", url: "https://coursera.org" },
{ title: "edX", desc: "Hochwertige Kurse von Harvard, MIT & Co.", url: "https://edx.org" },
{ title: "Udemy", desc: "Praxisnahe Videokurse zu fast jedem Thema.", url: "https://udemy.com" },
{ title: "Khan Academy", desc: "Kostenlose Lernplattform für Schüler und Studenten.", url: "https://khanacademy.org" },
{ title: "Brilliant", desc: "Interaktives Lernen für Mathe & Wissenschaft.", url: "https://brilliant.org" },
{ title: "Duolingo", desc: "Sprachen lernen spielerisch.", url: "https://duolingo.com" },
{ title: "OpenLearn", desc: "Kostenlose Kurse der Open University.", url: "https://open.edu/openlearn" },

// --- PROGRAMMIEREN & ENTWICKLUNG ---
{ title: "MDN Web Docs", desc: "Die beste Dokumentation für Webentwicklung.", url: "https://developer.mozilla.org" },
{ title: "W3Schools", desc: "Einsteigerfreundliche Tutorials für Web-Technologien.", url: "https://w3schools.com" },
{ title: "CodePen", desc: "Frontend-Code direkt im Browser testen.", url: "https://codepen.io" },
{ title: "Replit", desc: "Programmieren direkt im Browser.", url: "https://replit.com" },
{ title: "Glitch", desc: "Web-Apps online erstellen und hosten.", url: "https://glitch.com" },
{ title: "HackerRank", desc: "Programmier-Challenges & Wettbewerbe.", url: "https://hackerrank.com" },
{ title: "LeetCode", desc: "Coding-Interviews trainieren.", url: "https://leetcode.com" },
{ title: "Codewars", desc: "Programmieraufgaben im Kata-Stil.", url: "https://codewars.com" },

// --- WISSENSCHAFT & FORSCHUNG ---
{ title: "arXiv", desc: "Preprints aus Physik, Mathe & Informatik.", url: "https://arxiv.org" },
{ title: "Google Scholar", desc: "Wissenschaftliche Literatur finden.", url: "https://scholar.google.com" },
{ title: "ResearchGate", desc: "Netzwerk für Wissenschaftler.", url: "https://researchgate.net" },
{ title: "Our World in Data", desc: "Globale Statistiken & Datenvisualisierungen.", url: "https://ourworldindata.org" },
{ title: "Wolfram Alpha", desc: "Computational Knowledge Engine.", url: "https://wolframalpha.com" },

// --- PRODUKTIVITÄT ---
{ title: "Todoist", desc: "Intelligente Aufgabenverwaltung.", url: "https://todoist.com" },
{ title: "TickTick", desc: "ToDo-Liste mit Kalender & Gewohnheitstracker.", url: "https://ticktick.com" },
{ title: "Evernote", desc: "Notizen und Organisation.", url: "https://evernote.com" },
{ title: "ClickUp", desc: "All-in-One Projektmanagement.", url: "https://clickup.com" },
{ title: "Obsidian", desc: "Wissensdatenbank mit Markdown.", url: "https://obsidian.md" },

// --- CLOUD & HOSTING ---
{ title: "Vercel", desc: "Frontend-Hosting für moderne Webapps.", url: "https://vercel.com" },
{ title: "Netlify", desc: "Deploy von statischen Websites in Sekunden.", url: "https://netlify.com" },
{ title: "DigitalOcean", desc: "Cloud-Server einfach bereitstellen.", url: "https://digitalocean.com" },
{ title: "Heroku", desc: "Cloud-Plattform für Entwickler.", url: "https://heroku.com" },

// --- CYBERSECURITY ---
{ title: "Have I Been Pwned", desc: "Prüfe, ob deine E-Mail geleakt wurde.", url: "https://haveibeenpwned.com" },
{ title: "VirusTotal", desc: "Dateien und URLs auf Malware prüfen.", url: "https://virustotal.com" },
{ title: "Shodan", desc: "Suchmaschine für vernetzte Geräte.", url: "https://shodan.io" },

// --- KI & ZUKUNFT ---
{ title: "Hugging Face", desc: "Open-Source-Modelle für KI.", url: "https://huggingface.co" },
{ title: "OpenAI", desc: "Forschung und KI-Modelle.", url: "https://openai.com" },
{ title: "Runway ML", desc: "KI-Tools für Kreative.", url: "https://runwayml.com" },
{ title: "Leonardo AI", desc: "KI-Bildgenerierung.", url: "https://leonardo.ai" },

// --- FINANZEN ---
{ title: "TradingView", desc: "Charts & Marktanalyse für Trader.", url: "https://tradingview.com" },
{ title: "CoinMarketCap", desc: "Kryptowährungen verfolgen.", url: "https://coinmarketcap.com" },
{ title: "Yahoo Finance", desc: "Aktienkurse & Wirtschaftsnachrichten.", url: "https://finance.yahoo.com" },
{ title: "JustETF", desc: "ETF-Vergleich für Europa.", url: "https://justetf.com" },

// --- ENTERTAINMENT ---
{ title: "IMDb", desc: "Die größte Filmdatenbank der Welt.", url: "https://imdb.com" },
{ title: "Letterboxd", desc: "Filme bewerten & entdecken.", url: "https://letterboxd.com" },
{ title: "Crunchyroll", desc: "Anime-Streaming.", url: "https://crunchyroll.com" },
{ title: "SoundCloud", desc: "Musik entdecken & teilen.", url: "https://soundcloud.com" },

// --- LERNTHEMEN & WISSEN ---
{ title: "TED", desc: "Inspirierende Vorträge weltweit.", url: "https://ted.com" },
{ title: "Project Gutenberg", desc: "Kostenlose klassische Literatur.", url: "https://gutenberg.org" },
{ title: "Internet Archive", desc: "Digitale Bibliothek & Wayback Machine.", url: "https://archive.org" },

// --- NÜTZLICHE TOOLS ---
{ title: "TinyPNG", desc: "Bilder ohne Qualitätsverlust komprimieren.", url: "https://tinypng.com" },
{ title: "Remove.bg", desc: "Hintergrund automatisch entfernen.", url: "https://remove.bg" },
{ title: "ILovePDF", desc: "PDF-Dateien bearbeiten & konvertieren.", url: "https://ilovepdf.com" },
{ title: "Speedtest", desc: "Internetgeschwindigkeit testen.", url: "https://speedtest.net" },
{ title: "DownDetector", desc: "Prüfen, ob Dienste aktuell Probleme haben.", url: "https://downdetector.com" },

// --- KI & MACHINE LEARNING ---
{ title: "Anthropic", desc: "Claude KI und AI-Sicherheitsforschung.", url: "https://anthropic.com" },
{ title: "Stability AI", desc: "Entwickler von Stable Diffusion.", url: "https://stability.ai" },
{ title: "Midjourney", desc: "KI-Bildgenerierung über Discord.", url: "https://midjourney.com" },
{ title: "Replicate", desc: "KI-Modelle per API ausführen.", url: "https://replicate.com" },
{ title: "Papers with Code", desc: "Forschungspapiere mit Code verknüpft.", url: "https://paperswithcode.com" },
{ title: "Kaggle", desc: "Data-Science-Wettbewerbe & Datensätze.", url: "https://kaggle.com" },
{ title: "Fast.ai", desc: "Deep Learning Kurse & Bibliothek.", url: "https://fast.ai" },

// --- STARTUPS & TECH ---
{ title: "Product Hunt", desc: "Neue Tech-Produkte entdecken.", url: "https://producthunt.com" },
{ title: "AngelList", desc: "Startup Jobs & Investoren.", url: "https://wellfound.com" },
{ title: "Crunchbase", desc: "Datenbank für Startups & Firmen.", url: "https://crunchbase.com" },
{ title: "YC Hacker News", desc: "Tech-News & Diskussionen.", url: "https://news.ycombinator.com" },
{ title: "Indie Hackers", desc: "Community für Solo-Gründer.", url: "https://indiehackers.com" },

// --- DESIGN & UI ---
{ title: "Awwwards", desc: "Die besten Webdesigns weltweit.", url: "https://awwwards.com" },
{ title: "UI8", desc: "Premium UI Kits & Design Assets.", url: "https://ui8.net" },
{ title: "Mobbin", desc: "UI-Design Inspiration für Apps.", url: "https://mobbin.com" },
{ title: "LottieFiles", desc: "Animationen für Apps & Web.", url: "https://lottiefiles.com" },
{ title: "Icons8", desc: "Icons, Illustrationen & Musik.", url: "https://icons8.com" },

// --- DATEN & STATISTIK ---
{ title: "Statista", desc: "Marktdaten & Statistiken.", url: "https://statista.com" },
{ title: "World Bank Data", desc: "Globale Wirtschaftsdaten.", url: "https://data.worldbank.org" },
{ title: "OECD Data", desc: "Internationale Vergleichsdaten.", url: "https://data.oecd.org" },
{ title: "Gapminder", desc: "Interaktive Datenvisualisierung.", url: "https://gapminder.org" },

// --- CYBER & PRIVACY ---
{ title: "Proton", desc: "Schweizer E-Mail & VPN.", url: "https://proton.me" },
{ title: "NordVPN", desc: "VPN-Dienst für Privatsphäre.", url: "https://nordvpn.com" },
{ title: "PrivacyTools", desc: "Empfehlungen für digitale Sicherheit.", url: "https://privacyguides.org" },

// --- WISSENSCHAFT & SPACE ---
{ title: "CERN", desc: "Europäische Organisation für Kernforschung.", url: "https://cern.ch" },
{ title: "ESO", desc: "Europäische Südsternwarte.", url: "https://eso.org" },
{ title: "SETI Institute", desc: "Suche nach außerirdischem Leben.", url: "https://seti.org" },
{ title: "Planetary Society", desc: "Raumfahrtorganisation von Bill Nye.", url: "https://planetary.org" },

// --- FINTECH & KRYPTOWELT ---
{ title: "Binance", desc: "Kryptobörse weltweit.", url: "https://binance.com" },
{ title: "Kraken", desc: "Krypto-Handelsplattform.", url: "https://kraken.com" },
{ title: "CoinGecko", desc: "Krypto-Marktdaten.", url: "https://coingecko.com" },
{ title: "Glassnode", desc: "Blockchain-Analyseplattform.", url: "https://glassnode.com" },

// --- ENTWICKLER POWER ---
{ title: "Stack Exchange", desc: "Netzwerk spezialisierter Q&A Communities.", url: "https://stackexchange.com" },
{ title: "DevDocs", desc: "API-Dokumentationen offline nutzbar.", url: "https://devdocs.io" },
{ title: "Roadmap.sh", desc: "Karrierepfade für Entwickler.", url: "https://roadmap.sh" },
{ title: "Overleaf", desc: "LaTeX online schreiben.", url: "https://overleaf.com" },

// --- LERNEN & WISSEN ---
{ title: "MasterClass", desc: "Kurse von weltbekannten Experten.", url: "https://masterclass.com" },
{ title: "FutureLearn", desc: "Online-Kurse von Universitäten.", url: "https://futurelearn.com" },
{ title: "Saylor Academy", desc: "Kostenlose Hochschulkurse.", url: "https://saylor.org" },

// --- VIDEO & CONTENT CREATION ---
{ title: "CapCut", desc: "Beliebter Online-Videoeditor.", url: "https://capcut.com" },
{ title: "Descript", desc: "Audio & Video durch Text bearbeiten.", url: "https://descript.com" },
{ title: "Streamlabs", desc: "Tools für Streamer.", url: "https://streamlabs.com" },
{ title: "Patreon", desc: "Creator finanziell unterstützen.", url: "https://patreon.com" },

// --- TECH NEWS ---
{ title: "Ars Technica", desc: "Technologie & Wissenschaft.", url: "https://arstechnica.com" },
{ title: "ZDNet", desc: "IT-News & Business Tech.", url: "https://zdnet.com" },
{ title: "9to5Mac", desc: "Apple News & Leaks.", url: "https://9to5mac.com" },
{ title: "Android Authority", desc: "Android News & Reviews.", url: "https://androidauthority.com" },

// --- GEOGRAPHIE & KARTEN ---
{ title: "OpenStreetMap", desc: "Freie Weltkarte.", url: "https://openstreetmap.org" },
{ title: "GeoGuessr", desc: "Errate Orte weltweit anhand von Street View.", url: "https://geoguessr.com" },
{ title: "Windy", desc: "Live-Wetterkarten weltweit.", url: "https://windy.com" },

// --- MUSIK & AUDIO ---
{ title: "Bandcamp", desc: "Musik direkt von Künstlern kaufen.", url: "https://bandcamp.com" },
{ title: "Genius", desc: "Songtexte & Interpretationen.", url: "https://genius.com" },
{ title: "Last.fm", desc: "Musiktracking & Empfehlungen.", url: "https://last.fm" },

// --- GAMING INDUSTRY ---
{ title: "SteamDB", desc: "Statistiken & Preisverläufe für Steam.", url: "https://steamdb.info" },
{ title: "IsThereAnyDeal", desc: "Spielepreisvergleich.", url: "https://isthereanydeal.com" },
{ title: "Backloggd", desc: "Spiele bewerten & tracken.", url: "https://backloggd.com" },

// --- PRODUKTIVITÄT PRO ---
{ title: "Readwise", desc: "Markierungen aus Büchern sammeln.", url: "https://readwise.io" },
{ title: "Freedom", desc: "Ablenkende Websites blockieren.", url: "https://freedom.to" },
{ title: "RescueTime", desc: "Zeitanalyse deiner digitalen Nutzung.", url: "https://rescuetime.com" },

// --- COMMUNITY & DISKUSSION ---
{ title: "Discord Bots", desc: "Bot-Verzeichnis für Discord-Server.", url: "https://top.gg" },
{ title: "Meetup", desc: "Lokale Events & Communities.", url: "https://meetup.com" },
{ title: "Internations", desc: "Community für Expats weltweit.", url: "https://internations.org" },
// ============================================
// 🇨🇭 SCHWEIZ PREMIUM – BUND (ADMIN)
// ============================================

{ title: "admin.ch", desc: "Offizielle Website der Schweizerischen Eidgenossenschaft.", url: "https://admin.ch" },
{ title: "Bundesrat", desc: "Informationen zur Schweizer Regierung.", url: "https://bundesrat.admin.ch" },
{ title: "Parlament", desc: "National- und Ständerat.", url: "https://parlament.ch" },
{ title: "Bundesgericht", desc: "Oberstes Gericht der Schweiz.", url: "https://bger.ch" },
{ title: "Fedlex", desc: "Amtliche Sammlung des Bundesrechts.", url: "https://fedlex.admin.ch" },
{ title: "Swiss Post", desc: "Postdienste & Online-Services.", url: "https://post.ch" },
{ title: "Swiss Federal Railways", desc: "Bundesbahnen & Mobilität.", url: "https://sbb.ch" },
{ title: "Swissmedic", desc: "Schweizerisches Heilmittelinstitut.", url: "https://swissmedic.ch" },
{ title: "FINMA", desc: "Finanzmarktaufsicht Schweiz.", url: "https://finma.ch" },
{ title: "BAG", desc: "Bundesamt für Gesundheit.", url: "https://bag.admin.ch" },
{ title: "EDA", desc: "Eidgenössisches Departement für auswärtige Angelegenheiten.", url: "https://eda.admin.ch" },
{ title: "SECO", desc: "Staatssekretariat für Wirtschaft.", url: "https://seco.admin.ch" },
{ title: "MeteoSchweiz", desc: "Offizielle Wetterprognosen.", url: "https://meteoschweiz.admin.ch" },
{ title: "Swisstopo", desc: "Landesvermessung & Karten.", url: "https://swisstopo.admin.ch" },
{ title: "Open Data Schweiz", desc: "Offizielle Open-Data-Plattform.", url: "https://opendata.swiss" },

// ============================================
// 🇨🇭 KANTONE – OFFIZIELLE PORTALE
// ============================================

{ title: "Kanton Zürich", desc: "Offizielle Website des Kantons.", url: "https://zh.ch" },
{ title: "Kanton Bern", desc: "Behördenportal Bern.", url: "https://be.ch" },
{ title: "Kanton Luzern", desc: "Verwaltung Luzern.", url: "https://lu.ch" },
{ title: "Kanton Uri", desc: "Offizielles Kantonsportal.", url: "https://ur.ch" },
{ title: "Kanton Schwyz", desc: "Verwaltung Schwyz.", url: "https://sz.ch" },
{ title: "Kanton Obwalden", desc: "Offizielle Seite.", url: "https://ow.ch" },
{ title: "Kanton Nidwalden", desc: "Behördenportal.", url: "https://nw.ch" },
{ title: "Kanton Glarus", desc: "Kantonsverwaltung.", url: "https://gl.ch" },
{ title: "Kanton Zug", desc: "Kantonale Verwaltung.", url: "https://zg.ch" },
{ title: "Kanton Freiburg", desc: "Etat de Fribourg.", url: "https://fr.ch" },
{ title: "Kanton Solothurn", desc: "Kantonales Portal.", url: "https://so.ch" },
{ title: "Kanton Basel-Stadt", desc: "Regierung BS.", url: "https://bs.ch" },
{ title: "Kanton Basel-Landschaft", desc: "BL Verwaltung.", url: "https://bl.ch" },
{ title: "Kanton Schaffhausen", desc: "Offizielle Seite.", url: "https://sh.ch" },
{ title: "Kanton Appenzell A.Rh.", desc: "Kantonsverwaltung.", url: "https://ar.ch" },
{ title: "Kanton Appenzell I.Rh.", desc: "Kantonale Dienste.", url: "https://ai.ch" },
{ title: "Kanton St. Gallen", desc: "Behördenportal SG.", url: "https://sg.ch" },
{ title: "Kanton Graubünden", desc: "Amtliches Portal.", url: "https://gr.ch" },
{ title: "Kanton Aargau", desc: "Verwaltung AG.", url: "https://ag.ch" },
{ title: "Kanton Thurgau", desc: "Behörden TG.", url: "https://tg.ch" },
{ title: "Kanton Tessin", desc: "Cantone Ticino.", url: "https://ti.ch" },
{ title: "Kanton Waadt", desc: "Etat de Vaud.", url: "https://vd.ch" },
{ title: "Kanton Wallis", desc: "Canton du Valais.", url: "https://vs.ch" },
{ title: "Kanton Neuenburg", desc: "République et Canton.", url: "https://ne.ch" },
{ title: "Kanton Genf", desc: "République et Canton de Genève.", url: "https://ge.ch" },
{ title: "Kanton Jura", desc: "République et Canton du Jura.", url: "https://ju.ch" },

// ============================================
// 🇨🇭 STEUERN & VERWALTUNG
// ============================================

{ title: "ESTV", desc: "Eidgenössische Steuerverwaltung.", url: "https://estv.admin.ch" },
{ title: "AHV/IV", desc: "Sozialversicherungen Schweiz.", url: "https://ahv-iv.ch" },
{ title: "ch.ch", desc: "Behördenwegweiser Schweiz.", url: "https://ch.ch" },
{ title: "EasyGov", desc: "Online-Schalter für Unternehmen.", url: "https://easygov.swiss" },
{ title: "Handelsregister Zefix", desc: "Firmenregister Schweiz.", url: "https://zefix.admin.ch" },

// ============================================
// 🇨🇭 BILDUNG & UNIVERSITÄTEN
// ============================================

{ title: "ETH Zürich", desc: "Technische Hochschule Zürich.", url: "https://ethz.ch" },
{ title: "EPFL", desc: "École polytechnique fédérale de Lausanne.", url: "https://epfl.ch" },
{ title: "Universität Zürich", desc: "Größte Uni der Schweiz.", url: "https://uzh.ch" },
{ title: "Universität Bern", desc: "Uni Bern.", url: "https://unibe.ch" },
{ title: "Universität Basel", desc: "Älteste Universität der Schweiz.", url: "https://unibas.ch" },
{ title: "Universität Genf", desc: "Université de Genève.", url: "https://unige.ch" },
{ title: "Universität Lausanne", desc: "Université de Lausanne.", url: "https://unil.ch" },
{ title: "Universität Luzern", desc: "Uni Luzern.", url: "https://unilu.ch" },
{ title: "Universität St. Gallen", desc: "HSG – Wirtschaftsuniversität.", url: "https://unisg.ch" },

// ============================================
// 🇨🇭 WIRTSCHAFT & FINANZEN
// ============================================

{ title: "SIX Group", desc: "Betreiber der Schweizer Börse.", url: "https://six-group.com" },
{ title: "Swiss National Bank", desc: "Schweizerische Nationalbank.", url: "https://snb.ch" },
{ title: "Economiesuisse", desc: "Wirtschaftsverband Schweiz.", url: "https://economiesuisse.ch" },
{ title: "Swissmem", desc: "Industrieverband.", url: "https://swissmem.ch" },
{ title: "Switzerland Global Enterprise", desc: "Exportförderung.", url: "https://s-ge.com" },

// ============================================
// 🇨🇭 SICHERHEIT & JUSTIZ
// ============================================

{ title: "fedpol", desc: "Bundesamt für Polizei.", url: "https://fedpol.admin.ch" },
{ title: "NCSC", desc: "Nationales Zentrum für Cybersicherheit.", url: "https://ncsc.admin.ch" },
{ title: "Zivilschutz Schweiz", desc: "Bevölkerungsschutz.", url: "https://bevoelkerungsschutz.admin.ch" },

// ============================================
// 🇨🇭 TOURISMUS & KULTUR
// ============================================

{ title: "MySwitzerland", desc: "Offizielle Tourismusplattform.", url: "https://myswitzerland.com" },
{ title: "Pro Helvetia", desc: "Schweizer Kulturstiftung.", url: "https://prohelvetia.ch" },
{ title: "Swissinfo", desc: "Internationale News der Schweiz.", url: "https://swissinfo.ch" }
]; // <-- Das ist die wichtigste Zeile!
    
